/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sessionkotlin.dsl

import java.io.Serializable

@DslMarker
private annotation class SessionKotlinDSL

@SessionKotlinDSL
class GlobalEnv(declaredRoles: Set<Role>) {
    internal val interactions = mutableListOf<Interaction>()
    private val roles = declaredRoles.toMutableSet()

    /**
     *
     * Declares that [from] should send a message of type [T] to [to].
     *
     * @param [from] role that sends the message
     * @param [to] role that receives the message
     *
     * @throws [sessionkotlin.dsl.exception.SendingtoSelfException]
     * if [from] and [to] are the same.
     *
     * @sample [sessionkotlin.dsl.Examples.send]
     *
     */
    fun <T : Serializable> send(from: Role, to: Role) {
        val msg = Send<T>(from, to)
        roles.add(from)
        roles.add(to)

        interactions.add(msg)
    }

    /**
     *
     * Declares an internal choice at [at].
     *
     * @param [at] role that makes the decision
     * @param [cases] block that defines the choices
     *
     * @throws [sessionkotlin.dsl.exception.RoleNotEnabledException] if a role that is not enabled initiates an interaction.
     *
     * @sample [sessionkotlin.dsl.Examples.choice]
     *
     */
    fun choice(at: Role, cases: ChoiceEnv.() -> Unit) {
        val bEnv = ChoiceEnv(roles)
        bEnv.cases()
        val b = Branch(at, bEnv.caseMap)

        interactions.add(b)
        roles.add(at)
    }

    /**
     *
     * Appends a global protocol.
     *
     * @param [protocolBuilder] protocol to append
     * @param [mapping] mapping of roles to replace (optional)
     *
     * @sample [sessionkotlin.dsl.Examples.exec]
     *
     */
    fun exec(protocolBuilder: GlobalEnv, mapping: Map<Role, Role> = emptyMap()) {
        for (i in protocolBuilder.interactions) {
            interactions.add(i.with(mapping))
        }

    }

    fun dump(indent: Int = 0) {
        for (i in interactions) {
            i.dump(indent)
        }
    }
}

@SessionKotlinDSL
class ChoiceEnv(private val declaredRoles: Set<Role>) {
    internal val caseMap = mutableMapOf<String, GlobalEnv>()

    fun case(label: String, protocolBuilder: GlobalEnv.() -> Unit) {
        val p = GlobalEnv(declaredRoles)
        p.protocolBuilder()
        caseMap[label] = p
    }
}

fun globalProtocol(protocolBuilder: GlobalEnv.() -> Unit): GlobalEnv {
    val p = GlobalEnv(emptySet())
    p.protocolBuilder()
    return p
}