/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import sessionkotlin.dsl.GlobalEnv
import sessionkotlin.dsl.Role
import sessionkotlin.dsl.globalProtocol


fun main() {
    val a = Role("A")
    val b = Role("B")
    val c = Role("C")


    val case3 = globalProtocol {
        choice(b) {
            case("sub1") {
                send<Int>(b, c)
//                send<Int>(c, a)
                send<Int>(c, b)

            }
            case("sub2") {
                send<Int>(b, a)
            }
        }
    }

    val case2 = globalProtocol {
        send<String>(b, c)
    }

    globalProtocol {
        choice(b) {

            case("Case 1") {
                exec(case3)
            }
            case("Case 2") {
                exec(case2)
            }
        }
    }.dump()

}
