/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import sessionkotlin.dsl.GlobalEnv
import sessionkotlin.dsl.Role
import sessionkotlin.dsl.globalProtocol


fun main() {
    val a = Role("A")
    val b = Role("B")

    val g: GlobalEnv = globalProtocol {
        send<Int>(a, b)
        send<Int>(b, a)

        choice(b) {
            case("Case1") {
                send<String>(b, a)
            }
            case("Case2") {
                send<Int>(b, a)
            }
        }

    }
    g.debug()

//    val localA = LocalProtocol(g, a)
}
