/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import sessionkotlin.annotations.Project
import sessionkotlin.dsl.GlobalEnv
import sessionkotlin.dsl.LocalProtocol
import sessionkotlin.dsl.Role
import sessionkotlin.dsl.exception.InconsistentExternalChoiceException
import sessionkotlin.dsl.globalProtocol


fun main() {
    val a = Role("A")
    val b = Role("B")
    val c = Role("C")


    val case1 = globalProtocol {
        send<Int>(b, c)
        send<Int>(b, a)
    }

    val case2 = globalProtocol {
        send<String>(b, a)
        send<Int>(b, c)
    }

    val g = globalProtocol {
        choice(b) {

            case("Case 1") {
                exec(case1)
            }
            case("Case 2") {
                exec(case2)
            }
        }
    }

    @Project
    class LocalB(): LocalProtocol(g, b)


}
