/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sessionkotlin.annotations

@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class Project
