/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.1/userguide/building_java_projects.html
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.31"
    id("com.google.devtools.ksp") version "1.6.10-1.0.2"
    // Apply the java-library plugin for API and implementation separation.
    application
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.david:sessionkotlin_lib:0.0.1")
}

application {
    // Define the main class for the application.
    mainClass.set("protocol.AppKt")
}

kotlin.sourceSets.main {
    kotlin.srcDirs(
        file("$buildDir/generated"),
    )
}


